//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneServiceClientPrototype.PhoneHighScoreService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Platform", Namespace="http://schemas.datacontract.org/2004/07/PhoneHighScoreService")]
    public enum Platform : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Windows = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WindowsPhone = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surface = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneHighScoreService.IPhoneHighScoreService")]
    public interface IPhoneHighScoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneHighScoreService/AddHighScore_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/AddHighScore_PhoneResponse")]
        void AddHighScore_Phone(string s);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/AddHighScore_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/AddHighScore_PhoneResponse")]
        System.IAsyncResult BeginAddHighScore_Phone(string s, System.AsyncCallback callback, object asyncState);
        
        void EndAddHighScore_Phone(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGlobally_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGlobally_PhoneResponse")]
        string GetHighScoresGlobally_Phone(string gameTitle);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGlobally_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGlobally_PhoneResponse")]
        System.IAsyncResult BeginGetHighScoresGlobally_Phone(string gameTitle, System.AsyncCallback callback, object asyncState);
        
        string EndGetHighScoresGlobally_Phone(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatform_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatform_PhoneResponse")]
        string GetHighScoresForPlatform_Phone(PhoneServiceClientPrototype.PhoneHighScoreService.Platform p, string gameTitle);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatform_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatform_PhoneResponse")]
        System.IAsyncResult BeginGetHighScoresForPlatform_Phone(PhoneServiceClientPrototype.PhoneHighScoreService.Platform p, string gameTitle, System.AsyncCallback callback, object asyncState);
        
        string EndGetHighScoresForPlatform_Phone(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneHighScoreServiceChannel : PhoneServiceClientPrototype.PhoneHighScoreService.IPhoneHighScoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHighScoresGlobally_PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHighScoresGlobally_PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHighScoresForPlatform_PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHighScoresForPlatform_PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneHighScoreServiceClient : System.ServiceModel.ClientBase<PhoneServiceClientPrototype.PhoneHighScoreService.IPhoneHighScoreService>, PhoneServiceClientPrototype.PhoneHighScoreService.IPhoneHighScoreService {
        
        private BeginOperationDelegate onBeginAddHighScore_PhoneDelegate;
        
        private EndOperationDelegate onEndAddHighScore_PhoneDelegate;
        
        private System.Threading.SendOrPostCallback onAddHighScore_PhoneCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHighScoresGlobally_PhoneDelegate;
        
        private EndOperationDelegate onEndGetHighScoresGlobally_PhoneDelegate;
        
        private System.Threading.SendOrPostCallback onGetHighScoresGlobally_PhoneCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHighScoresForPlatform_PhoneDelegate;
        
        private EndOperationDelegate onEndGetHighScoresForPlatform_PhoneDelegate;
        
        private System.Threading.SendOrPostCallback onGetHighScoresForPlatform_PhoneCompletedDelegate;
        
        public PhoneHighScoreServiceClient() {
        }
        
        public PhoneHighScoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneHighScoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneHighScoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneHighScoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddHighScore_PhoneCompleted;
        
        public event System.EventHandler<GetHighScoresGlobally_PhoneCompletedEventArgs> GetHighScoresGlobally_PhoneCompleted;
        
        public event System.EventHandler<GetHighScoresForPlatform_PhoneCompletedEventArgs> GetHighScoresForPlatform_PhoneCompleted;
        
        public void AddHighScore_Phone(string s) {
            base.Channel.AddHighScore_Phone(s);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddHighScore_Phone(string s, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddHighScore_Phone(s, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddHighScore_Phone(System.IAsyncResult result) {
            base.Channel.EndAddHighScore_Phone(result);
        }
        
        private System.IAsyncResult OnBeginAddHighScore_Phone(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string s = ((string)(inValues[0]));
            return this.BeginAddHighScore_Phone(s, callback, asyncState);
        }
        
        private object[] OnEndAddHighScore_Phone(System.IAsyncResult result) {
            this.EndAddHighScore_Phone(result);
            return null;
        }
        
        private void OnAddHighScore_PhoneCompleted(object state) {
            if ((this.AddHighScore_PhoneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddHighScore_PhoneCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddHighScore_PhoneAsync(string s) {
            this.AddHighScore_PhoneAsync(s, null);
        }
        
        public void AddHighScore_PhoneAsync(string s, object userState) {
            if ((this.onBeginAddHighScore_PhoneDelegate == null)) {
                this.onBeginAddHighScore_PhoneDelegate = new BeginOperationDelegate(this.OnBeginAddHighScore_Phone);
            }
            if ((this.onEndAddHighScore_PhoneDelegate == null)) {
                this.onEndAddHighScore_PhoneDelegate = new EndOperationDelegate(this.OnEndAddHighScore_Phone);
            }
            if ((this.onAddHighScore_PhoneCompletedDelegate == null)) {
                this.onAddHighScore_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddHighScore_PhoneCompleted);
            }
            base.InvokeAsync(this.onBeginAddHighScore_PhoneDelegate, new object[] {
                        s}, this.onEndAddHighScore_PhoneDelegate, this.onAddHighScore_PhoneCompletedDelegate, userState);
        }
        
        public string GetHighScoresGlobally_Phone(string gameTitle) {
            return base.Channel.GetHighScoresGlobally_Phone(gameTitle);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetHighScoresGlobally_Phone(string gameTitle, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHighScoresGlobally_Phone(gameTitle, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetHighScoresGlobally_Phone(System.IAsyncResult result) {
            return base.Channel.EndGetHighScoresGlobally_Phone(result);
        }
        
        private System.IAsyncResult OnBeginGetHighScoresGlobally_Phone(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string gameTitle = ((string)(inValues[0]));
            return this.BeginGetHighScoresGlobally_Phone(gameTitle, callback, asyncState);
        }
        
        private object[] OnEndGetHighScoresGlobally_Phone(System.IAsyncResult result) {
            string retVal = this.EndGetHighScoresGlobally_Phone(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHighScoresGlobally_PhoneCompleted(object state) {
            if ((this.GetHighScoresGlobally_PhoneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHighScoresGlobally_PhoneCompleted(this, new GetHighScoresGlobally_PhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHighScoresGlobally_PhoneAsync(string gameTitle) {
            this.GetHighScoresGlobally_PhoneAsync(gameTitle, null);
        }
        
        public void GetHighScoresGlobally_PhoneAsync(string gameTitle, object userState) {
            if ((this.onBeginGetHighScoresGlobally_PhoneDelegate == null)) {
                this.onBeginGetHighScoresGlobally_PhoneDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresGlobally_Phone);
            }
            if ((this.onEndGetHighScoresGlobally_PhoneDelegate == null)) {
                this.onEndGetHighScoresGlobally_PhoneDelegate = new EndOperationDelegate(this.OnEndGetHighScoresGlobally_Phone);
            }
            if ((this.onGetHighScoresGlobally_PhoneCompletedDelegate == null)) {
                this.onGetHighScoresGlobally_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresGlobally_PhoneCompleted);
            }
            base.InvokeAsync(this.onBeginGetHighScoresGlobally_PhoneDelegate, new object[] {
                        gameTitle}, this.onEndGetHighScoresGlobally_PhoneDelegate, this.onGetHighScoresGlobally_PhoneCompletedDelegate, userState);
        }
        
        public string GetHighScoresForPlatform_Phone(PhoneServiceClientPrototype.PhoneHighScoreService.Platform p, string gameTitle) {
            return base.Channel.GetHighScoresForPlatform_Phone(p, gameTitle);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetHighScoresForPlatform_Phone(PhoneServiceClientPrototype.PhoneHighScoreService.Platform p, string gameTitle, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHighScoresForPlatform_Phone(p, gameTitle, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetHighScoresForPlatform_Phone(System.IAsyncResult result) {
            return base.Channel.EndGetHighScoresForPlatform_Phone(result);
        }
        
        private System.IAsyncResult OnBeginGetHighScoresForPlatform_Phone(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneServiceClientPrototype.PhoneHighScoreService.Platform p = ((PhoneServiceClientPrototype.PhoneHighScoreService.Platform)(inValues[0]));
            string gameTitle = ((string)(inValues[1]));
            return this.BeginGetHighScoresForPlatform_Phone(p, gameTitle, callback, asyncState);
        }
        
        private object[] OnEndGetHighScoresForPlatform_Phone(System.IAsyncResult result) {
            string retVal = this.EndGetHighScoresForPlatform_Phone(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHighScoresForPlatform_PhoneCompleted(object state) {
            if ((this.GetHighScoresForPlatform_PhoneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHighScoresForPlatform_PhoneCompleted(this, new GetHighScoresForPlatform_PhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHighScoresForPlatform_PhoneAsync(PhoneServiceClientPrototype.PhoneHighScoreService.Platform p, string gameTitle) {
            this.GetHighScoresForPlatform_PhoneAsync(p, gameTitle, null);
        }
        
        public void GetHighScoresForPlatform_PhoneAsync(PhoneServiceClientPrototype.PhoneHighScoreService.Platform p, string gameTitle, object userState) {
            if ((this.onBeginGetHighScoresForPlatform_PhoneDelegate == null)) {
                this.onBeginGetHighScoresForPlatform_PhoneDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresForPlatform_Phone);
            }
            if ((this.onEndGetHighScoresForPlatform_PhoneDelegate == null)) {
                this.onEndGetHighScoresForPlatform_PhoneDelegate = new EndOperationDelegate(this.OnEndGetHighScoresForPlatform_Phone);
            }
            if ((this.onGetHighScoresForPlatform_PhoneCompletedDelegate == null)) {
                this.onGetHighScoresForPlatform_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresForPlatform_PhoneCompleted);
            }
            base.InvokeAsync(this.onBeginGetHighScoresForPlatform_PhoneDelegate, new object[] {
                        p,
                        gameTitle}, this.onEndGetHighScoresForPlatform_PhoneDelegate, this.onGetHighScoresForPlatform_PhoneCompletedDelegate, userState);
        }
    }
}
