//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClientPrototype.HighScoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HighScore", Namespace="http://schemas.datacontract.org/2004/07/HighScoreService")]
    [System.SerializableAttribute()]
    public partial class HighScore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceClientPrototype.HighScoreService.Platform PlatformIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TransmittedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameTitle {
            get {
                return this.GameTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.GameTitleField, value) != true)) {
                    this.GameTitleField = value;
                    this.RaisePropertyChanged("GameTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceClientPrototype.HighScoreService.Platform PlatformID {
            get {
                return this.PlatformIDField;
            }
            set {
                if ((this.PlatformIDField.Equals(value) != true)) {
                    this.PlatformIDField = value;
                    this.RaisePropertyChanged("PlatformID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Transmitted {
            get {
                return this.TransmittedField;
            }
            set {
                if ((this.TransmittedField.Equals(value) != true)) {
                    this.TransmittedField = value;
                    this.RaisePropertyChanged("Transmitted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Platform", Namespace="http://schemas.datacontract.org/2004/07/HighScoreService")]
    public enum Platform : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Windows = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WindowsPhone = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surface = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HighScoreService.IHighScoreService")]
    public interface IHighScoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighScoreService/AddHighScore", ReplyAction="http://tempuri.org/IHighScoreService/AddHighScoreResponse")]
        void AddHighScore(ServiceClientPrototype.HighScoreService.HighScore hs);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHighScoreService/AddHighScore", ReplyAction="http://tempuri.org/IHighScoreService/AddHighScoreResponse")]
        System.IAsyncResult BeginAddHighScore(ServiceClientPrototype.HighScoreService.HighScore hs, System.AsyncCallback callback, object asyncState);
        
        void EndAddHighScore(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighScoreService/GetHighScoresGlobally", ReplyAction="http://tempuri.org/IHighScoreService/GetHighScoresGloballyResponse")]
        ServiceClientPrototype.HighScoreService.HighScore[] GetHighScoresGlobally(string gameTitle);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHighScoreService/GetHighScoresGlobally", ReplyAction="http://tempuri.org/IHighScoreService/GetHighScoresGloballyResponse")]
        System.IAsyncResult BeginGetHighScoresGlobally(string gameTitle, System.AsyncCallback callback, object asyncState);
        
        ServiceClientPrototype.HighScoreService.HighScore[] EndGetHighScoresGlobally(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighScoreService/GetHighScoresForPlatform", ReplyAction="http://tempuri.org/IHighScoreService/GetHighScoresForPlatformResponse")]
        ServiceClientPrototype.HighScoreService.HighScore[] GetHighScoresForPlatform(ServiceClientPrototype.HighScoreService.Platform p, string gameTitle);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHighScoreService/GetHighScoresForPlatform", ReplyAction="http://tempuri.org/IHighScoreService/GetHighScoresForPlatformResponse")]
        System.IAsyncResult BeginGetHighScoresForPlatform(ServiceClientPrototype.HighScoreService.Platform p, string gameTitle, System.AsyncCallback callback, object asyncState);
        
        ServiceClientPrototype.HighScoreService.HighScore[] EndGetHighScoresForPlatform(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHighScoreServiceChannel : ServiceClientPrototype.HighScoreService.IHighScoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHighScoresGloballyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHighScoresGloballyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ServiceClientPrototype.HighScoreService.HighScore[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ServiceClientPrototype.HighScoreService.HighScore[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHighScoresForPlatformCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHighScoresForPlatformCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ServiceClientPrototype.HighScoreService.HighScore[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ServiceClientPrototype.HighScoreService.HighScore[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HighScoreServiceClient : System.ServiceModel.ClientBase<ServiceClientPrototype.HighScoreService.IHighScoreService>, ServiceClientPrototype.HighScoreService.IHighScoreService {
        
        private BeginOperationDelegate onBeginAddHighScoreDelegate;
        
        private EndOperationDelegate onEndAddHighScoreDelegate;
        
        private System.Threading.SendOrPostCallback onAddHighScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHighScoresGloballyDelegate;
        
        private EndOperationDelegate onEndGetHighScoresGloballyDelegate;
        
        private System.Threading.SendOrPostCallback onGetHighScoresGloballyCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHighScoresForPlatformDelegate;
        
        private EndOperationDelegate onEndGetHighScoresForPlatformDelegate;
        
        private System.Threading.SendOrPostCallback onGetHighScoresForPlatformCompletedDelegate;
        
        public HighScoreServiceClient() {
        }
        
        public HighScoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HighScoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HighScoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HighScoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddHighScoreCompleted;
        
        public event System.EventHandler<GetHighScoresGloballyCompletedEventArgs> GetHighScoresGloballyCompleted;
        
        public event System.EventHandler<GetHighScoresForPlatformCompletedEventArgs> GetHighScoresForPlatformCompleted;
        
        public void AddHighScore(ServiceClientPrototype.HighScoreService.HighScore hs) {
            base.Channel.AddHighScore(hs);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddHighScore(ServiceClientPrototype.HighScoreService.HighScore hs, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddHighScore(hs, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddHighScore(System.IAsyncResult result) {
            base.Channel.EndAddHighScore(result);
        }
        
        private System.IAsyncResult OnBeginAddHighScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ServiceClientPrototype.HighScoreService.HighScore hs = ((ServiceClientPrototype.HighScoreService.HighScore)(inValues[0]));
            return this.BeginAddHighScore(hs, callback, asyncState);
        }
        
        private object[] OnEndAddHighScore(System.IAsyncResult result) {
            this.EndAddHighScore(result);
            return null;
        }
        
        private void OnAddHighScoreCompleted(object state) {
            if ((this.AddHighScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddHighScoreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddHighScoreAsync(ServiceClientPrototype.HighScoreService.HighScore hs) {
            this.AddHighScoreAsync(hs, null);
        }
        
        public void AddHighScoreAsync(ServiceClientPrototype.HighScoreService.HighScore hs, object userState) {
            if ((this.onBeginAddHighScoreDelegate == null)) {
                this.onBeginAddHighScoreDelegate = new BeginOperationDelegate(this.OnBeginAddHighScore);
            }
            if ((this.onEndAddHighScoreDelegate == null)) {
                this.onEndAddHighScoreDelegate = new EndOperationDelegate(this.OnEndAddHighScore);
            }
            if ((this.onAddHighScoreCompletedDelegate == null)) {
                this.onAddHighScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddHighScoreCompleted);
            }
            base.InvokeAsync(this.onBeginAddHighScoreDelegate, new object[] {
                        hs}, this.onEndAddHighScoreDelegate, this.onAddHighScoreCompletedDelegate, userState);
        }
        
        public ServiceClientPrototype.HighScoreService.HighScore[] GetHighScoresGlobally(string gameTitle) {
            return base.Channel.GetHighScoresGlobally(gameTitle);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetHighScoresGlobally(string gameTitle, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHighScoresGlobally(gameTitle, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ServiceClientPrototype.HighScoreService.HighScore[] EndGetHighScoresGlobally(System.IAsyncResult result) {
            return base.Channel.EndGetHighScoresGlobally(result);
        }
        
        private System.IAsyncResult OnBeginGetHighScoresGlobally(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string gameTitle = ((string)(inValues[0]));
            return this.BeginGetHighScoresGlobally(gameTitle, callback, asyncState);
        }
        
        private object[] OnEndGetHighScoresGlobally(System.IAsyncResult result) {
            ServiceClientPrototype.HighScoreService.HighScore[] retVal = this.EndGetHighScoresGlobally(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHighScoresGloballyCompleted(object state) {
            if ((this.GetHighScoresGloballyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHighScoresGloballyCompleted(this, new GetHighScoresGloballyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHighScoresGloballyAsync(string gameTitle) {
            this.GetHighScoresGloballyAsync(gameTitle, null);
        }
        
        public void GetHighScoresGloballyAsync(string gameTitle, object userState) {
            if ((this.onBeginGetHighScoresGloballyDelegate == null)) {
                this.onBeginGetHighScoresGloballyDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresGlobally);
            }
            if ((this.onEndGetHighScoresGloballyDelegate == null)) {
                this.onEndGetHighScoresGloballyDelegate = new EndOperationDelegate(this.OnEndGetHighScoresGlobally);
            }
            if ((this.onGetHighScoresGloballyCompletedDelegate == null)) {
                this.onGetHighScoresGloballyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresGloballyCompleted);
            }
            base.InvokeAsync(this.onBeginGetHighScoresGloballyDelegate, new object[] {
                        gameTitle}, this.onEndGetHighScoresGloballyDelegate, this.onGetHighScoresGloballyCompletedDelegate, userState);
        }
        
        public ServiceClientPrototype.HighScoreService.HighScore[] GetHighScoresForPlatform(ServiceClientPrototype.HighScoreService.Platform p, string gameTitle) {
            return base.Channel.GetHighScoresForPlatform(p, gameTitle);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetHighScoresForPlatform(ServiceClientPrototype.HighScoreService.Platform p, string gameTitle, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHighScoresForPlatform(p, gameTitle, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ServiceClientPrototype.HighScoreService.HighScore[] EndGetHighScoresForPlatform(System.IAsyncResult result) {
            return base.Channel.EndGetHighScoresForPlatform(result);
        }
        
        private System.IAsyncResult OnBeginGetHighScoresForPlatform(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ServiceClientPrototype.HighScoreService.Platform p = ((ServiceClientPrototype.HighScoreService.Platform)(inValues[0]));
            string gameTitle = ((string)(inValues[1]));
            return this.BeginGetHighScoresForPlatform(p, gameTitle, callback, asyncState);
        }
        
        private object[] OnEndGetHighScoresForPlatform(System.IAsyncResult result) {
            ServiceClientPrototype.HighScoreService.HighScore[] retVal = this.EndGetHighScoresForPlatform(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHighScoresForPlatformCompleted(object state) {
            if ((this.GetHighScoresForPlatformCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHighScoresForPlatformCompleted(this, new GetHighScoresForPlatformCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHighScoresForPlatformAsync(ServiceClientPrototype.HighScoreService.Platform p, string gameTitle) {
            this.GetHighScoresForPlatformAsync(p, gameTitle, null);
        }
        
        public void GetHighScoresForPlatformAsync(ServiceClientPrototype.HighScoreService.Platform p, string gameTitle, object userState) {
            if ((this.onBeginGetHighScoresForPlatformDelegate == null)) {
                this.onBeginGetHighScoresForPlatformDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresForPlatform);
            }
            if ((this.onEndGetHighScoresForPlatformDelegate == null)) {
                this.onEndGetHighScoresForPlatformDelegate = new EndOperationDelegate(this.OnEndGetHighScoresForPlatform);
            }
            if ((this.onGetHighScoresForPlatformCompletedDelegate == null)) {
                this.onGetHighScoresForPlatformCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresForPlatformCompleted);
            }
            base.InvokeAsync(this.onBeginGetHighScoresForPlatformDelegate, new object[] {
                        p,
                        gameTitle}, this.onEndGetHighScoresForPlatformDelegate, this.onGetHighScoresForPlatformCompletedDelegate, userState);
        }
    }
}
