//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhaleRiderSim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhaleRiderSim.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each bad query takes away one late day.
        /// </summary>
        internal static string AvoidBadQueries {
            get {
                return ResourceManager.GetString("AvoidBadQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\ButtonFont.
        /// </summary>
        internal static string Button_font {
            get {
                return ResourceManager.GetString("Button_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\CodeFont.
        /// </summary>
        internal static string Code_font {
            get {
                return ResourceManager.GetString("Code_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect SQL Items
        ///in Correct Order.
        /// </summary>
        internal static string CollectSQL {
            get {
                return ResourceManager.GetString("CollectSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current SQL Query.
        /// </summary>
        internal static string CurrQuery {
            get {
                return ResourceManager.GetString("CurrQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge Injection Attacks.
        /// </summary>
        internal static string DodgeInjection {
            get {
                return ResourceManager.GetString("DodgeInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\HeaderFont.
        /// </summary>
        internal static string FirstInstHeader_font {
            get {
                return ResourceManager.GetString("FirstInstHeader_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Scores.
        /// </summary>
        internal static string HighScore {
            get {
                return ResourceManager.GetString("HighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\HeaderFont.
        /// </summary>
        internal static string HighScoresHeader_font {
            get {
                return ResourceManager.GetString("HighScoresHeader_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Your Late Days!.
        /// </summary>
        internal static string KeepYourLateDays {
            get {
                return ResourceManager.GetString("KeepYourLateDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\HeaderFont.
        /// </summary>
        internal static string LoseHeader_font {
            get {
                return ResourceManager.GetString("LoseHeader_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Name.
        /// </summary>
        internal static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not reach the high
        ///scores server. Try again later!.
        /// </summary>
        internal static string NoRemoteServer {
            get {
                return ResourceManager.GetString("NoRemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\HeaderFont.
        /// </summary>
        internal static string PausedHeader_font {
            get {
                return ResourceManager.GetString("PausedHeader_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving High Score....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect SQL Queries for Points!.
        /// </summary>
        internal static string SecondInstHeader {
            get {
                return ResourceManager.GetString("SecondInstHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\HeaderFont.
        /// </summary>
        internal static string SecondInstHeader_font {
            get {
                return ResourceManager.GetString("SecondInstHeader_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\HeaderFont.
        /// </summary>
        internal static string SettingsHeader_font {
            get {
                return ResourceManager.GetString("SettingsHeader_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\SimpleFont.
        /// </summary>
        internal static string Simple_font {
            get {
                return ResourceManager.GetString("Simple_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sriram&apos;s Whale Riding 101.
        /// </summary>
        internal static string Title_Screen {
            get {
                return ResourceManager.GetString("Title_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts\HeaderFont.
        /// </summary>
        internal static string TitleHeader_font {
            get {
                return ResourceManager.GetString("TitleHeader_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail!.
        /// </summary>
        internal static string YouLose {
            get {
                return ResourceManager.GetString("YouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When all of your late days are gone, you lose!.
        /// </summary>
        internal static string YouLoseWhen {
            get {
                return ResourceManager.GetString("YouLoseWhen", resourceCulture);
            }
        }
    }
}
