//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 3.7.0.0
// 
namespace PhoneHighScoreService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Platform", Namespace="http://schemas.datacontract.org/2004/07/PhoneHighScoreService")]
    public enum Platform : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Windows = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WindowsPhone = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surface = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPhoneHighScoreService")]
public interface IPhoneHighScoreService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/AddHighScore_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/AddHighScore_PhoneResponse")]
    System.IAsyncResult BeginAddHighScore_Phone(string s, System.AsyncCallback callback, object asyncState);
    
    void EndAddHighScore_Phone(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGlobally_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGlobally_PhoneResponse")]
    System.IAsyncResult BeginGetHighScoresGlobally_Phone(string gameTitle, System.AsyncCallback callback, object asyncState);
    
    string EndGetHighScoresGlobally_Phone(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatform_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatform_PhoneResponse")]
    System.IAsyncResult BeginGetHighScoresForPlatform_Phone(PhoneHighScoreService.Platform p, string gameTitle, System.AsyncCallback callback, object asyncState);
    
    string EndGetHighScoresForPlatform_Phone(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGloballyv2_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresGloballyv2_PhoneResponse")]
    System.IAsyncResult BeginGetHighScoresGloballyv2_Phone(string gameTitle, int mode, System.AsyncCallback callback, object asyncState);
    
    string EndGetHighScoresGloballyv2_Phone(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatformv2_Phone", ReplyAction="http://tempuri.org/IPhoneHighScoreService/GetHighScoresForPlatformv2_PhoneRespons" +
        "e")]
    System.IAsyncResult BeginGetHighScoresForPlatformv2_Phone(PhoneHighScoreService.Platform p, string gameTitle, int mode, System.AsyncCallback callback, object asyncState);
    
    string EndGetHighScoresForPlatformv2_Phone(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPhoneHighScoreServiceChannel : IPhoneHighScoreService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetHighScoresGlobally_PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetHighScoresGlobally_PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetHighScoresForPlatform_PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetHighScoresForPlatform_PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetHighScoresGloballyv2_PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetHighScoresGloballyv2_PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetHighScoresForPlatformv2_PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetHighScoresForPlatformv2_PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PhoneHighScoreServiceClient : System.ServiceModel.ClientBase<IPhoneHighScoreService>, IPhoneHighScoreService
{
    
    private BeginOperationDelegate onBeginAddHighScore_PhoneDelegate;
    
    private EndOperationDelegate onEndAddHighScore_PhoneDelegate;
    
    private System.Threading.SendOrPostCallback onAddHighScore_PhoneCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetHighScoresGlobally_PhoneDelegate;
    
    private EndOperationDelegate onEndGetHighScoresGlobally_PhoneDelegate;
    
    private System.Threading.SendOrPostCallback onGetHighScoresGlobally_PhoneCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetHighScoresForPlatform_PhoneDelegate;
    
    private EndOperationDelegate onEndGetHighScoresForPlatform_PhoneDelegate;
    
    private System.Threading.SendOrPostCallback onGetHighScoresForPlatform_PhoneCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetHighScoresGloballyv2_PhoneDelegate;
    
    private EndOperationDelegate onEndGetHighScoresGloballyv2_PhoneDelegate;
    
    private System.Threading.SendOrPostCallback onGetHighScoresGloballyv2_PhoneCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetHighScoresForPlatformv2_PhoneDelegate;
    
    private EndOperationDelegate onEndGetHighScoresForPlatformv2_PhoneDelegate;
    
    private System.Threading.SendOrPostCallback onGetHighScoresForPlatformv2_PhoneCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public PhoneHighScoreServiceClient()
    {
    }
    
    public PhoneHighScoreServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PhoneHighScoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhoneHighScoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhoneHighScoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddHighScore_PhoneCompleted;
    
    public event System.EventHandler<GetHighScoresGlobally_PhoneCompletedEventArgs> GetHighScoresGlobally_PhoneCompleted;
    
    public event System.EventHandler<GetHighScoresForPlatform_PhoneCompletedEventArgs> GetHighScoresForPlatform_PhoneCompleted;
    
    public event System.EventHandler<GetHighScoresGloballyv2_PhoneCompletedEventArgs> GetHighScoresGloballyv2_PhoneCompleted;
    
    public event System.EventHandler<GetHighScoresForPlatformv2_PhoneCompletedEventArgs> GetHighScoresForPlatformv2_PhoneCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IPhoneHighScoreService.BeginAddHighScore_Phone(string s, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddHighScore_Phone(s, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IPhoneHighScoreService.EndAddHighScore_Phone(System.IAsyncResult result)
    {
        base.Channel.EndAddHighScore_Phone(result);
    }
    
    private System.IAsyncResult OnBeginAddHighScore_Phone(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string s = ((string)(inValues[0]));
        return ((IPhoneHighScoreService)(this)).BeginAddHighScore_Phone(s, callback, asyncState);
    }
    
    private object[] OnEndAddHighScore_Phone(System.IAsyncResult result)
    {
        ((IPhoneHighScoreService)(this)).EndAddHighScore_Phone(result);
        return null;
    }
    
    private void OnAddHighScore_PhoneCompleted(object state)
    {
        if ((this.AddHighScore_PhoneCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.AddHighScore_PhoneCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void AddHighScore_PhoneAsync(string s)
    {
        this.AddHighScore_PhoneAsync(s, null);
    }
    
    public void AddHighScore_PhoneAsync(string s, object userState)
    {
        if ((this.onBeginAddHighScore_PhoneDelegate == null))
        {
            this.onBeginAddHighScore_PhoneDelegate = new BeginOperationDelegate(this.OnBeginAddHighScore_Phone);
        }
        if ((this.onEndAddHighScore_PhoneDelegate == null))
        {
            this.onEndAddHighScore_PhoneDelegate = new EndOperationDelegate(this.OnEndAddHighScore_Phone);
        }
        if ((this.onAddHighScore_PhoneCompletedDelegate == null))
        {
            this.onAddHighScore_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddHighScore_PhoneCompleted);
        }
        base.InvokeAsync(this.onBeginAddHighScore_PhoneDelegate, new object[] {
                    s}, this.onEndAddHighScore_PhoneDelegate, this.onAddHighScore_PhoneCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IPhoneHighScoreService.BeginGetHighScoresGlobally_Phone(string gameTitle, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetHighScoresGlobally_Phone(gameTitle, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IPhoneHighScoreService.EndGetHighScoresGlobally_Phone(System.IAsyncResult result)
    {
        return base.Channel.EndGetHighScoresGlobally_Phone(result);
    }
    
    private System.IAsyncResult OnBeginGetHighScoresGlobally_Phone(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string gameTitle = ((string)(inValues[0]));
        return ((IPhoneHighScoreService)(this)).BeginGetHighScoresGlobally_Phone(gameTitle, callback, asyncState);
    }
    
    private object[] OnEndGetHighScoresGlobally_Phone(System.IAsyncResult result)
    {
        string retVal = ((IPhoneHighScoreService)(this)).EndGetHighScoresGlobally_Phone(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetHighScoresGlobally_PhoneCompleted(object state)
    {
        if ((this.GetHighScoresGlobally_PhoneCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetHighScoresGlobally_PhoneCompleted(this, new GetHighScoresGlobally_PhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetHighScoresGlobally_PhoneAsync(string gameTitle)
    {
        this.GetHighScoresGlobally_PhoneAsync(gameTitle, null);
    }
    
    public void GetHighScoresGlobally_PhoneAsync(string gameTitle, object userState)
    {
        if ((this.onBeginGetHighScoresGlobally_PhoneDelegate == null))
        {
            this.onBeginGetHighScoresGlobally_PhoneDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresGlobally_Phone);
        }
        if ((this.onEndGetHighScoresGlobally_PhoneDelegate == null))
        {
            this.onEndGetHighScoresGlobally_PhoneDelegate = new EndOperationDelegate(this.OnEndGetHighScoresGlobally_Phone);
        }
        if ((this.onGetHighScoresGlobally_PhoneCompletedDelegate == null))
        {
            this.onGetHighScoresGlobally_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresGlobally_PhoneCompleted);
        }
        base.InvokeAsync(this.onBeginGetHighScoresGlobally_PhoneDelegate, new object[] {
                    gameTitle}, this.onEndGetHighScoresGlobally_PhoneDelegate, this.onGetHighScoresGlobally_PhoneCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IPhoneHighScoreService.BeginGetHighScoresForPlatform_Phone(PhoneHighScoreService.Platform p, string gameTitle, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetHighScoresForPlatform_Phone(p, gameTitle, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IPhoneHighScoreService.EndGetHighScoresForPlatform_Phone(System.IAsyncResult result)
    {
        return base.Channel.EndGetHighScoresForPlatform_Phone(result);
    }
    
    private System.IAsyncResult OnBeginGetHighScoresForPlatform_Phone(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        PhoneHighScoreService.Platform p = ((PhoneHighScoreService.Platform)(inValues[0]));
        string gameTitle = ((string)(inValues[1]));
        return ((IPhoneHighScoreService)(this)).BeginGetHighScoresForPlatform_Phone(p, gameTitle, callback, asyncState);
    }
    
    private object[] OnEndGetHighScoresForPlatform_Phone(System.IAsyncResult result)
    {
        string retVal = ((IPhoneHighScoreService)(this)).EndGetHighScoresForPlatform_Phone(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetHighScoresForPlatform_PhoneCompleted(object state)
    {
        if ((this.GetHighScoresForPlatform_PhoneCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetHighScoresForPlatform_PhoneCompleted(this, new GetHighScoresForPlatform_PhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetHighScoresForPlatform_PhoneAsync(PhoneHighScoreService.Platform p, string gameTitle)
    {
        this.GetHighScoresForPlatform_PhoneAsync(p, gameTitle, null);
    }
    
    public void GetHighScoresForPlatform_PhoneAsync(PhoneHighScoreService.Platform p, string gameTitle, object userState)
    {
        if ((this.onBeginGetHighScoresForPlatform_PhoneDelegate == null))
        {
            this.onBeginGetHighScoresForPlatform_PhoneDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresForPlatform_Phone);
        }
        if ((this.onEndGetHighScoresForPlatform_PhoneDelegate == null))
        {
            this.onEndGetHighScoresForPlatform_PhoneDelegate = new EndOperationDelegate(this.OnEndGetHighScoresForPlatform_Phone);
        }
        if ((this.onGetHighScoresForPlatform_PhoneCompletedDelegate == null))
        {
            this.onGetHighScoresForPlatform_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresForPlatform_PhoneCompleted);
        }
        base.InvokeAsync(this.onBeginGetHighScoresForPlatform_PhoneDelegate, new object[] {
                    p,
                    gameTitle}, this.onEndGetHighScoresForPlatform_PhoneDelegate, this.onGetHighScoresForPlatform_PhoneCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IPhoneHighScoreService.BeginGetHighScoresGloballyv2_Phone(string gameTitle, int mode, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetHighScoresGloballyv2_Phone(gameTitle, mode, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IPhoneHighScoreService.EndGetHighScoresGloballyv2_Phone(System.IAsyncResult result)
    {
        return base.Channel.EndGetHighScoresGloballyv2_Phone(result);
    }
    
    private System.IAsyncResult OnBeginGetHighScoresGloballyv2_Phone(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string gameTitle = ((string)(inValues[0]));
        int mode = ((int)(inValues[1]));
        return ((IPhoneHighScoreService)(this)).BeginGetHighScoresGloballyv2_Phone(gameTitle, mode, callback, asyncState);
    }
    
    private object[] OnEndGetHighScoresGloballyv2_Phone(System.IAsyncResult result)
    {
        string retVal = ((IPhoneHighScoreService)(this)).EndGetHighScoresGloballyv2_Phone(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetHighScoresGloballyv2_PhoneCompleted(object state)
    {
        if ((this.GetHighScoresGloballyv2_PhoneCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetHighScoresGloballyv2_PhoneCompleted(this, new GetHighScoresGloballyv2_PhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetHighScoresGloballyv2_PhoneAsync(string gameTitle, int mode)
    {
        this.GetHighScoresGloballyv2_PhoneAsync(gameTitle, mode, null);
    }
    
    public void GetHighScoresGloballyv2_PhoneAsync(string gameTitle, int mode, object userState)
    {
        if ((this.onBeginGetHighScoresGloballyv2_PhoneDelegate == null))
        {
            this.onBeginGetHighScoresGloballyv2_PhoneDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresGloballyv2_Phone);
        }
        if ((this.onEndGetHighScoresGloballyv2_PhoneDelegate == null))
        {
            this.onEndGetHighScoresGloballyv2_PhoneDelegate = new EndOperationDelegate(this.OnEndGetHighScoresGloballyv2_Phone);
        }
        if ((this.onGetHighScoresGloballyv2_PhoneCompletedDelegate == null))
        {
            this.onGetHighScoresGloballyv2_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresGloballyv2_PhoneCompleted);
        }
        base.InvokeAsync(this.onBeginGetHighScoresGloballyv2_PhoneDelegate, new object[] {
                    gameTitle,
                    mode}, this.onEndGetHighScoresGloballyv2_PhoneDelegate, this.onGetHighScoresGloballyv2_PhoneCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IPhoneHighScoreService.BeginGetHighScoresForPlatformv2_Phone(PhoneHighScoreService.Platform p, string gameTitle, int mode, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetHighScoresForPlatformv2_Phone(p, gameTitle, mode, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IPhoneHighScoreService.EndGetHighScoresForPlatformv2_Phone(System.IAsyncResult result)
    {
        return base.Channel.EndGetHighScoresForPlatformv2_Phone(result);
    }
    
    private System.IAsyncResult OnBeginGetHighScoresForPlatformv2_Phone(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        PhoneHighScoreService.Platform p = ((PhoneHighScoreService.Platform)(inValues[0]));
        string gameTitle = ((string)(inValues[1]));
        int mode = ((int)(inValues[2]));
        return ((IPhoneHighScoreService)(this)).BeginGetHighScoresForPlatformv2_Phone(p, gameTitle, mode, callback, asyncState);
    }
    
    private object[] OnEndGetHighScoresForPlatformv2_Phone(System.IAsyncResult result)
    {
        string retVal = ((IPhoneHighScoreService)(this)).EndGetHighScoresForPlatformv2_Phone(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetHighScoresForPlatformv2_PhoneCompleted(object state)
    {
        if ((this.GetHighScoresForPlatformv2_PhoneCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetHighScoresForPlatformv2_PhoneCompleted(this, new GetHighScoresForPlatformv2_PhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetHighScoresForPlatformv2_PhoneAsync(PhoneHighScoreService.Platform p, string gameTitle, int mode)
    {
        this.GetHighScoresForPlatformv2_PhoneAsync(p, gameTitle, mode, null);
    }
    
    public void GetHighScoresForPlatformv2_PhoneAsync(PhoneHighScoreService.Platform p, string gameTitle, int mode, object userState)
    {
        if ((this.onBeginGetHighScoresForPlatformv2_PhoneDelegate == null))
        {
            this.onBeginGetHighScoresForPlatformv2_PhoneDelegate = new BeginOperationDelegate(this.OnBeginGetHighScoresForPlatformv2_Phone);
        }
        if ((this.onEndGetHighScoresForPlatformv2_PhoneDelegate == null))
        {
            this.onEndGetHighScoresForPlatformv2_PhoneDelegate = new EndOperationDelegate(this.OnEndGetHighScoresForPlatformv2_Phone);
        }
        if ((this.onGetHighScoresForPlatformv2_PhoneCompletedDelegate == null))
        {
            this.onGetHighScoresForPlatformv2_PhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighScoresForPlatformv2_PhoneCompleted);
        }
        base.InvokeAsync(this.onBeginGetHighScoresForPlatformv2_PhoneDelegate, new object[] {
                    p,
                    gameTitle,
                    mode}, this.onEndGetHighScoresForPlatformv2_PhoneDelegate, this.onGetHighScoresForPlatformv2_PhoneCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IPhoneHighScoreService CreateChannel()
    {
        return new PhoneHighScoreServiceClientChannel(this);
    }
    
    private class PhoneHighScoreServiceClientChannel : ChannelBase<IPhoneHighScoreService>, IPhoneHighScoreService
    {
        
        public PhoneHighScoreServiceClientChannel(System.ServiceModel.ClientBase<IPhoneHighScoreService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginAddHighScore_Phone(string s, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = s;
            System.IAsyncResult _result = base.BeginInvoke("AddHighScore_Phone", _args, callback, asyncState);
            return _result;
        }
        
        public void EndAddHighScore_Phone(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("AddHighScore_Phone", _args, result);
        }
        
        public System.IAsyncResult BeginGetHighScoresGlobally_Phone(string gameTitle, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = gameTitle;
            System.IAsyncResult _result = base.BeginInvoke("GetHighScoresGlobally_Phone", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetHighScoresGlobally_Phone(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetHighScoresGlobally_Phone", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetHighScoresForPlatform_Phone(PhoneHighScoreService.Platform p, string gameTitle, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = p;
            _args[1] = gameTitle;
            System.IAsyncResult _result = base.BeginInvoke("GetHighScoresForPlatform_Phone", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetHighScoresForPlatform_Phone(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetHighScoresForPlatform_Phone", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetHighScoresGloballyv2_Phone(string gameTitle, int mode, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = gameTitle;
            _args[1] = mode;
            System.IAsyncResult _result = base.BeginInvoke("GetHighScoresGloballyv2_Phone", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetHighScoresGloballyv2_Phone(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetHighScoresGloballyv2_Phone", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetHighScoresForPlatformv2_Phone(PhoneHighScoreService.Platform p, string gameTitle, int mode, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = p;
            _args[1] = gameTitle;
            _args[2] = mode;
            System.IAsyncResult _result = base.BeginInvoke("GetHighScoresForPlatformv2_Phone", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetHighScoresForPlatformv2_Phone(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetHighScoresForPlatformv2_Phone", _args, result)));
            return _result;
        }
    }
}
